### ISSUE TITLE
Classify Sample Points for Landsat 5 and 7

### ISSUE THREAD

**Issue by cjthomas730** [SkyTruth/MTR#21]
We need to classify points across the range of Landsat 5 dates to check if calibration changes to the sensor affect the threshold which is used to detect MTR sites. We also need to classify points for Landsat 7.

Points are to be classified into 2 categories: Active MTR sites (1) and anything other than active MTR (0).

Years to test:
 - [x] 2006 --> Landsat 7
 - [x] 1995 --> Landsat 5
 - [x] 1989 --> Landsat 5
 - [x] 1984 --> Landsat 5

@TwigBeard this is the [script](https://code.earthengine.google.com/20c1206fe1739e4924990cb70e732633) you will use to export true-color Landsat Images and Vegetation Indices. See me when you get in and we can go over the details of the export process.

**Comment by cjthomas730** [comment]
@TwigBeard attach a link to the google sheet where the points are classified in your MTR wiki page, then close this issue

**Comment by cjthomas730** [comment]
@TwigBeard please post the link so we can close the issue

**Comment by TwigBeard** [comment]
https://docs.google.com/a/skytruth.org/spreadsheets/d/1BYu0naaI5Y4bF3icg1RWyxgTp1NyGzBMJ4syNY65nXQ/edit?usp=sharing
