### ISSUE TITLE
Brady's Screenshots

### ISSUE THREAD

**Issue by TwigBeard** [SkyTruth/MTR#25]
Figure 1.
![comp-1984-ex](https://cloud.githubusercontent.com/assets/17166201/15189968/89220a7a-177b-11e6-9c5a-87a9533be538.png)
Figure 2.
![ndvi-1984-ex](https://cloud.githubusercontent.com/assets/17166201/15189972/8c8adc78-177b-11e6-866a-033714586e9d.png)

**Comment by cjthomas730** [comment]
@TwigBeard why don't you upload these pictures to Google Drive, and include the links in the wiki page
