### ISSUE TITLE
Earth Engine 1985

### ISSUE THREAD

**Issue by TwigBeard** [SkyTruth/MTR#26]
Google Earth Engine's Landsat5 imagery collection for 1985 seems to be displaying some kind of artifacts. They are strips obviously not collected from that area and it's affecting our NDVI classification. 

@cjthomas730

**Comment by cjthomas730** [comment]
The issues with 1985 imagery seem to stem from cloud's being present in the imagery, for data testing we can use imagery from 1986 as a proxy, but should also look in to what is causing the issues with the 85 imagery (maybe there aren't enough scenes to compute a good greenest pixel composite?). Alternatively we can consider using the imagery John has on cd from the USGS to produce our own composite.
