### ISSUE TITLE
Landsat 1-3

### ISSUE THREAD

**Issue by cjthomas730** [SkyTruth/MTR#29]
Write script to create annual greenest pixel composites for Landsat 1-3 imagery
-we will likely need to test and use a different NDVI threshold because no TOA products are available for these

**Comment by apericak** [comment]
Just FYI, I started looking at this today, which involved performing the TOA calculations by hand (in the script) since GEE doesn't have those layers available. I'll let you all know when I have this mostly complete.

**Comment by apericak** [comment]
Alright well I went through the trouble of hard-coding the digital number -> radiance -> reflectance process into working code, which you can see here: https://code.earthengine.google.com/347464658fa81afd4bbd0714bdd06127 Had a lot of fun writing that, I'm proud of it. But....

Then I found [this forum post](https://groups.google.com/d/msg/google-earth-engine-developers/G4hysmwcBZ0/-SQmL74rDgAJ) saying that as of just a few weeks ago, `ee.Algorithms.Landsat.TOA` actually supports all Landsat sensors now, even though the documentation hasn't been updated yet. And sure enough, that is the case. So here's the shorter, updated script that does that: https://code.earthengine.google.com/f953c96b01eb93716860dce92a6d54a2

The quality of the data from these early sensors isn't that great, but it does improve when looking at two or three years at a time. Something to consider, whether we want yearly snapshots for these early sensors.

**Comment by apericak** [comment]
I've spent a fair amount of time updating this script, in particular to filter out likely cloud areas and to filter out errors inherent in this early imagery. You can view the current version here: https://code.earthengine.google.com/637c1b034fa489c80808984ff590eb33 The problem right now, though, is that this runs very slowly, so I'm open to hearing suggestions about speeding it up!

**Comment by cjthomas730** [comment]
@apericak this is great, thanks for putting the time into getting this together

**Comment by WassonMF** [comment]
This is looking really good, Andrew. And I really like your suggestion of
using multi-year greenest pixel composites for the early years of Landsat -
it solves all kinds of problems at very little cost in terms of the
usefulness of the dataset. Not sure why this simple solution never even
entered my head as a possibility.

Great job with all this - and thanks for commenting your code so nicely!
Seems like you're off to an excellent start.

Matt

On Mon, Jun 20, 2016 at 4:06 PM, cjthomas730 <notifications@github.com>
wrote:

> @apericak <https://github.com/apericak> this is great, thanks for putting
> the time into getting this together
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/SkyTruth/MTR/issues/29#issuecomment-227253671>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ALCbI_vmAqZ2EWToCMFaa-bMrYXeXSxEks5qNvK3gaJpZM4Imjl8>
> .
>



-- 
Matthew F. Wasson, Ph.D., Director of Programs
Appalachian Voices

171 Grand Blvd.
Boone, NC 28607
Phone: 828-262-1500
Website: www.appalachianvoices.org

"Nonviolent action, born of the awareness of suffering and nurtured by
love, is the most effective way to confront adversity."

- *Thich Nhat Hanh, Love In Action*

**Comment by WassonMF** [comment]
@apericak: maybe it's just my exceedingly non-binary brain, but I find it a whole lot easier to interpret NDVI images in color. Accordingly, I just wanted to offer a paqlette that I find quite useful for viewing your script:

Map.addLayer(greenest, {bands:"NDVI", min:0.2, max:0.8, palette: 'FFFFFF, CE7E45, DF923D, F1B555, FCD163, 99B718, 74A901, 66A000, 529400, 3E8601, 207401, 056201, 004C00, 023B01, 012E01, 011D01, 011301'}, "NDVI");

In addition, I find it useful to look at this image in combination with the mask layer with a 60m buffer, so you can really see how mines are popping out without worrying about parking lots in the valleys and all that. In case you all find this helpful and it saves you a little time, I figured I'd offer the code I'm using for that as well:

var mask_input = ee.Image('GME/images/06136759344167181854-02242958771191394493');
var mask_result = mask_input.mask(mask_input); 
Map.addLayer(mask_result, {palette: '000000'}, 'Original Mask');

**Comment by apericak** [comment]
@WassonMF Thanks for the ideas, and yah I agree those definitely help with the visualization. Here's the updated script for everybody including those changes: https://code.earthengine.google.com/29e6f8a6653ff38018ef32410f7bd500 (Also in the LS123 branch).
