### ISSUE TITLE
VI (for days) Analysis

### ISSUE THREAD

**Issue by TwigBeard** [SkyTruth/MTR#30]
**Year** | **Tita's Threshold(0.54) Agreement** | **Our Threshold(0.51) Agreement** |
------------|--------------------------------------------------|-------------------------------------------------|
1984 | 98.33333333333 | 99.2222222222222 |
1986 | 98.33333333333 | 98.8888888888888 |
1987 | 98.33333333333 | 99.2222222222222 |
1989 | 98.33333333333 | 99.5555555555556 |
1995 | 98.33333333333 | 98.55555556 | 
2002 | 98.33333333333 | 99.2222222222222 | 
2012 | 98.33333333333 | 99.3333333333333 |

**Comment by ezys** [comment]
Interesting @TwigBeard What's unique about 1989? Your threshold exceeds Tita's in every year except '89.

**Comment by TwigBeard** [comment]
That was definitely odd, and I took a look at it. Most of the false positives were in the first 300 points, and didn't make sense (it said I classified mining over an NDVI value of for example 0.7). As it turns out, I entered the wrong NDVI values for the first 300 points. After pasting the correct NDVI values the percent agreement went from 97.888888888 to 99.555555556.

**Comment by cjthomas730** [comment]
@TwigBeard record this information in your MTR wiki page, and explain what you were testing
