### ISSUE TITLE
Updating the Magic Mask

### ISSUE THREAD

**Issue by TwigBeard** [SkyTruth/MTR#31]
Our updated script has classified a long strip at this location: (-82.08, 37.64). It seems to be a new coal-mining-related road, with access to a lovely football field (Go Miners). The other location (-84.09, 36.98) indicates some new urban development. The pictures below illustrates that our magic mask needs to be updated to include new urban areas. 

![screen shot 2016-06-07 at 10 23 49 am](https://cloud.githubusercontent.com/assets/17166201/15861361/2dc1bbf6-2c9a-11e6-8e25-034137854eea.png)

![screen shot 2016-06-07 at 12 31 57 pm](https://cloud.githubusercontent.com/assets/17166201/15866276/f9f272ae-2cab-11e6-8ac7-33859d90fc35.png)

**Comment by cjthomas730** [comment]
addressed in #45 , closing
