### ISSUE TITLE
EE Historic Scripts

### ISSUE THREAD

**Issue by cjthomas730** [SkyTruth/MTR#32]
@geowurster here's the list of scripts. It is worth noting that the 60m mask must be imported as an asset into Earth Engine in order to run there is a link to the mask [here](https://drive.google.com/file/d/0ByjSOOGMRVf5aUpLa01aX0FXR0U/view?usp=sharing).

1. Original Script (Tita's): https://code.earthengine.google.com/5bde4a99fe6073d99dbb6cda67b28a92

2. Tita's Script Annotated: https://code.earthengine.google.com/93f060594e882f4ce02796cee7d46fde

3. Script for WVAGP Conference: https://code.earthengine.google.com/9956a099a4943857a8ba8f415dec3f33

4. 5/23/2016: https://code.earthengine.google.com/dffc3927308289e8ed7820d9573673b4

5. 5/31/2016: https://code.earthengine.google.com/4c0a0c54e2829124b4ba3fa597ead05d

6. 06/06/2016: https://code.earthengine.google.com/ab8d52d77326f1087990190aadccb0d5

**Comment by geowurster** [comment]
@cjthomas730 Don't forget to hit `Delete branch` after merging (assuming the branch should be deleted, which is usually true).
