### ISSUE TITLE
Updating the MTR Mask Using 2015 Data

### ISSUE THREAD

**Issue by cjthomas730** [SkyTruth/MTR#35]
@JerrilynGoldberg, we would like to update our existing mask using data from the US Census Bureau's Tiger/Line Dataset. 

You'll need to download the following for each of the counties mentioned in #13 :
- [x] Area Hydrology
- [x] Linear Hydrology
- [x] Roads
- [x] Urban Areas
- [x] Military Installations
- [x] Protected Lands

These will also be downloaded for WV counties (the number of which pending on John's decision).

After you've downloaded these, they will need to be merged, buffered, and rasterized. Please make note of the processing the data goes through in a google doc, so that we will have a file on hand for the creation process of the mask.

**Comment by cjthomas730** [comment]
@JerrilynGoldberg is this going to the write email?

**Comment by cjthomas730** [comment]
See #45

**Comment by JerrilynGoldberg** [comment]
A link to the updated mask with complete study area as of 7.1.16: https://drive.google.com/a/skytruth.org/file/d/0B_MArPTqurHuY19vVEdWSjlCbjA/view?usp=sharing

**Comment by JerrilynGoldberg** [comment]
[And here is the EE component](https://code.earthengine.google.com/02735123c1cc17dcf08530ae1d06e56a)
