### ISSUE TITLE
Things To Do Before Publishing

### ISSUE THREAD

**Issue by davidkroodsma** [SkyTruth/MTR#40]
# To do by July 24th, 2016
- [x] Consolidate issues (Christian)
- [x] Get permit data and verify it (next conversation with app voices / Andrew)
- [x] Figure out optimum size for erode / dilate and get rid of small areas and make sure that they are reasonable (Andrew)
- [x] Make our own greenest pixel composite, especially for more recent years (Andrew)
- [x] Identify and get rid of cloud noise (email EE team about this) (Andrew / Christian)
- [x] Optimize threshold by year and/or sensor (Andrew / Brady)
- [x] Figure out plan for how to test accuracy by year (Andrew)
- [x] Execute plan on testing accuracy (Andrew /Brady)
- [x] Get updated mask (Jerrilyn & Christian)
- [x] Meet with Nick at the end of July (David)
- [x] set up second day for meeting (Christian)
# To do After July 25th
- [x] Stuffs that Nick told us to do
- [ ] Figure out pixel trajectory and make sure that our results make sense
- [ ] Figure out how to interpret when a mine is "recovered"
- [x] Figure out web visualization (David & Christian)
- [ ] Transfer to the Python API (Kevin & David)
- [x] Read other papers about this / Lit Review

**Comment by cjthomas730** [comment]
Data for the updated mask can be found in #45

**Comment by cjthomas730** [comment]
Now obsolete, moving the pertinent remaining tasks to: #111
