### ISSUE TITLE
Update Mask and Document the Steps for mask creation

### ISSUE THREAD

**Issue by cjthomas730** [SkyTruth/MTR#45]
@JerrilynGoldberg we want to create and update version of our 2014 MTR mask as well as document the steps for its creation. To include: 
- datasources
- CL tools used
- standardized order for the different operations being run

We will also work to optimize the mask creation for future years.

**Comment by cjthomas730** [comment]
The mask has been updated using 2015 data, as has the overall study area (see #55) by Jerrilyn.
The study area extent is available as a [fusion table here](https://www.google.com/fusiontables/DataSource?docid=1Lphn5PR9YbneoY4sPkKGMUOJcurihIcCx0J82h7U). @JerrilynGoldberg will you please post a link to the mask once it finishes uploading.

**Comment by JerrilynGoldberg** [comment]
A link to the updated mask with complete study area as of 7.1.16: https://drive.google.com/open?id=0B_MArPTqurHudTNEaUptMkpoTzA

[And the EE part](https://code.earthengine.google.com/02735123c1cc17dcf08530ae1d06e56a)

(also in #35 sorry)

**Comment by cjthomas730** [comment]
@JerrilynGoldberg when you do the write-up it would also be good to include some images which show the differences between the two masks (i.e. total area covered, example(s) of areas which one mask covers that the other does not)

**Comment by JerrilynGoldberg** [comment]
[here is the updated mask as of 7.8.16](https://drive.google.com/open?id=0B_MArPTqurHudFp6STU4ZzJHRmc)
and here is the line from the newest script with this tif
```java
var mask_input_60m_2015_update = ee.Image("users/jerrilyn/2015mask-PM-fullstudy-area");
Map.addLayer(mask_input_60m_2015_update, {min:0, max:1},'2015-Mask', false);
```
