### ISSUE TITLE
Identify and Remove Cloud Noise

### ISSUE THREAD

**Issue by cjthomas730** [SkyTruth/MTR#47]
_Blocks #49_
We will work to mask and remove cloud noise from our Greenest Pixel Composites (possibly using similar methods to what you did with the L1-L3 composite scripts @apericak ?) for the Landsat satellites being used in the MTR identification script.

**Comment by cjthomas730** [comment]
@apericak I think this was also addressed in #60? And while we need to develop a contingency for years which have cloud issues due to low scene collection numbers, the Greenest Pixel Compositing should take care of the issue of clouds?

**Comment by apericak** [comment]
@cjthomas730 Sortof--the early Landsats are really the ones suffering low scene numbers. There are some years in the later LSs, though, that also exhibit a lot of cloud noise despite using a greenest pixel composite. These are instances where a certain flight path clearly exhibits a lot of cloud noise. In these paths, though, the image still has NDVI values at those locations, so there's a chance the threshold for the year might nonetheless reveal a mine / not-mine, despite cloud noise. So in short, I think we'll have to wait and see about those particular years (and those flight paths) until we run the classification the first time. Then, we may have to do something about those specific areas with cloud contamination.
