### ISSUE TITLE
Identify region of interest (i.e., Central Appalachian Counties)

### ISSUE THREAD

**Issue by WassonMF** [SkyTruth/MTR#55]
Here are the counties that meet the following criteria:

Are (1) within the "Central Appalachia" region as defined by the Appalachian Regional Commission

AND
- (2a) Have reported surface coal production in at least one year since 1983
- AND / OR
- (2b) Have abandoned mine land sites in OSMRE's Abandoned Mine Land Inventory System (AMLIS)

A flat text file is attached and the results are also pasted below:

WV:
Pocahontas
Greenbrier
Nicholas
Clay 
Kanawha
Putnam
Mason
Cabell
Lincoln
Boone
Raleigh
Fayette
Summers
Mercer
Wyoming
McDowell
Mingo
Logan
Wayne

VA:
Tazewell
Buchanan
Dickenson
Russell
Wise
Scott
Lee
Norton (City)

TN:
Claiborne
Campbell
Anderson 
Scott
Roane
Morgan
Fentress
Pickett
Overton
Putnam
Cumberland

KY:
Clinton
Wayne
McCreary
Pulaski
Rockastle
Laurel
Whitley
Jackson
Estill
Owsley
Lee
Powell
Menifee
Wolfe
Morgan
Rowan
Elliott
Carter
Lewis
Greenup
Boyd
Lawrence
Johnson
Martin
Magoffin
Breathitt
Pike
Floyd
Knott
Perry
Letcher
Harlan
Leslie
Bell
Knox
Clay

[CAPP_Counties.txt](https://github.com/SkyTruth/MTR/files/341888/CAPP_Counties.txt)

**Comment by JerrilynGoldberg** [comment]
Got it!

**Comment by cjthomas730** [comment]
The study area has been updated using the above criteria, closing the issue
