### ISSUE TITLE
Updated Mask Issues

### ISSUE THREAD

**Issue by TwigBeard** [SkyTruth/MTR#57]
After downloading script-classified mines for 2015, I noticed that a large portion of urban area was identified from Huntington along the Ohio River continuously over to Kanawha River. Moreover, the script has also identified large portions of the Ohio River, and other large waterways. 

![screen shot 2016-07-06 at 4 24 36 pm](https://cloud.githubusercontent.com/assets/17166201/16633224/42f27106-4396-11e6-8a6d-4a0e909f2fff.png)
The large portion on the left is the Huntington, WV area.

**Comment by cjthomas730** [comment]
The issue seems to be that the mask doesn't cover the entirety of the updated study area. It currently only extends to the Campagna study area boundary

**Comment by JerrilynGoldberg** [comment]
https://code.earthengine.google.com/f9102ff2ee340c18b78fa651e7e8d26f here is the updated stuff, please let me know if the sharing setting need updating.

**Comment by JerrilynGoldberg** [comment]
https://code.earthengine.google.com/e7669dc544b25f61073bd69caa3efaca

JK

**Comment by cjthomas730** [comment]
@TwigBeard see #45, the mask is now updated
