### ISSUE TITLE
Conduct Accuracy Assessment

### ISSUE THREAD

**Issue by cjthomas730** [SkyTruth/MTR#76]
_See #68 for background_

We are ready to begin the point classification process which we will use for our statistical analysis.

The directions are found in the [Point Analysis Process document](https://docs.google.com/document/d/17fCGPUnbbacOqLktLYMiHYlVM8Gj2xwbI4L9MHSfsSc/edit?usp=sharing), please read before you begin.

The sample points are in [this spreadsheet](https://docs.google.com/spreadsheets/d/1Niqgf-GnGAJNce7Tr_BvEEGEy0taY0kn4dmutnLMFn4/edit?usp=sharing).

Record the output of your classifications in [this spreadsheet](https://docs.google.com/spreadsheets/d/1vCxZ_L5e8Kyu-Ei2zkg-mPEEmRqrohppc09nMyNd43g/edit?usp=sharing)

**Comment by apericak** [comment]
I've skipped Kappa 2012 due to few if any mining points

**Comment by JerrilynGoldberg** [comment]
I've skipped Kappa 2002 for the same reason.

**Comment by cjthomas730** [comment]
1999 has the same issue

**Comment by cjthomas730** [comment]
@apericak it looks like the point classification is very close to finished (~90%). The only remaining areas have been classified as error years. I'll look through the non-kappa sites which still have error classifications and see if I can make some sense of them.

**Comment by cjthomas730** [comment]
@apericak I believe I've found a suitable replacement area for kappa

**Comment by apericak** [comment]
@cjthomas730 Great, whenever you have time you can create the random points as you did before. I can help create the RGB, if you want.

**Comment by cjthomas730** [comment]
@apericak I updated the spreadsheets, and removed Kappa from the Output Classifications sheet

**Comment by cjthomas730** [comment]
@apericak , here's the final sample area.
__EPSG:3857__ [Omega_area_EPSG-3857.zip](https://github.com/SkyTruth/MTR/files/448095/Omega_area_EPSG-3857.zip)

__EPSG:5072__ [Omega_area_EPSG-5072.zip](https://github.com/SkyTruth/MTR/files/448096/Omega_area_EPSG-5072.zip)
