### ISSUE TITLE
Develop method and scripts for running accuracy assessment

### ISSUE THREAD

**Issue by apericak** [SkyTruth/MTR#84]
As we approach the end of #76 (manually classifying a bunch of points), we should start developing our method for actually conducting the accuracy assessment. We will, at a minimum, want to create confusion matrices per year, and probably some of the other scores discussed on [this Wikipedia page.](https://en.wikipedia.org/wiki/Confusion_matrix). 

Earth Engine does have built-in confusion matrix methods (see the `ee.ConfusionMatrix` tab in the Docs on the playground), so since we have so many points and so many years, we will likely want to write a new script to accomplish this.

**Comment by apericak** [comment]
For reference, here's what @cjthomas730 had accomplished as of 12 August 2016:  https://code.earthengine.google.com/a6b45f1f4c067e1adcb8569bebb71350

**Comment by cjthomas730** [comment]
Here's the update as of 09/02: https://code.earthengine.google.com/e06d7ff71307408ddd952977a99d9972

**Comment by apericak** [comment]
This is addressed in #98, so once those changes are accepted we can close this issue (and thanks @cjthomas730 for researching and writing the code to make this accuracy assessment work!)
