### ISSUE TITLE
Develop pixel trajectory code

### ISSUE THREAD

**Issue by apericak** [SkyTruth/MTR#85]
Given what we've learned about cloud filtering (see #83 and #47), we will most likely have some areas in some years with null values, because those areas had too many clouds for us to get accurate NDVI data. To fill in the gaps, wherever possible, we should use the "pixel trajectory" concept. If we have a null value pixel in 2014 due to cloud cover, for example, but that same pixel in 2013 and 2015 is a mine, then we can assume the 2014 pixel is also a mine. We will want code to go through our classification images and perform this cleaning operation. 

Note that this only works where the two years immediately adjacent a null year are the same (i.e., they are both mines or both non-mines.) We will have to leave null any pixels that are mines in 2013, null in 2014, and non-mines in 2015 (for example).

**Comment by apericak** [comment]
@cjthomas730 This version of pixel trajectory that I was mentioning here (look to prior and future years to clean errors/null pixels) is now built in to our script, so I propose we close this issue. A longer-term issue (perhaps to open, although it's essentially what we're looking at in #75) is running the pixel trajectory concept of looking at each image to plot NDVI, as @davidkroodsma has been looking at

**Comment by cjthomas730** [comment]
Will link to this in #111
